name: Build release

on:
  push:
      branches:
        - main
      tags:
        - v*

  pull_request:
      branches:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: |
          gradle --version
          gradle wrapper
          ./gradlew clean assembleDebug
      - run: tree
      - name: Archive apk
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: 'app/build/outputs/apk/debug/app-debug.apk'
      - name: Add apk to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: 'app/build/outputs/apk/debug/app-debug.apk'
